spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/banking"
    username: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

